apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
  namespace: elastic-system
spec:
  version: 8.3.2
  count: 1
  http:
    service:
      spec:
        type: NodePort
        ports:
          - port: 5601
            targetPort: 5601
            name: http
            nodePort: 5601

  # config:
  #   elasticsearch.hosts:
  #     - https://eck-cluster-es-default.elastic-system:9200
  #   elasticsearch.username: kibana
  # secureSettings:
  #   - secretName: kibana-elasticsearch-credentials
  image: 192.168.110.44:5000/elastic/kibana:8.3.2
  elasticsearchRef:
    name: "eck-cluster"
  config:
    elasticsearch.requestHeadersWhitelist:
    - authorization
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kibana-nodeport
#   namespace: elastic-system
# spec:
#   externalTrafficPolicy: Cluster
#   ports:
#   - name: http
#     nodePort: 5601
#     port: 5601
#     protocol: TCP
#     targetPort: 5601
#   selector:
#     common.k8s.elastic.co/type: kibana
#     kibana.k8s.elastic.co/name: kibana-sample
#   sessionAffinity: None
#   type: NodePort
# status:
#   loadBalancer: {}
