kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: prometheus
  name: prometheus-service
  namespace: ns-monitor
spec:
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 26000
  selector:
    app: prometheus
  type: NodePort