# nfs-client的自动装载程序安装
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  namespace: middleware
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
      - name: nfs-client-provisioner
        # image: quay.io/external_storage/nfs-client-provisioner:latest
        image: 192.168.110.44:5000/external_storage/nfs-client-provisioner:latest
        volumeMounts:
        - name: nfs-client-root
          mountPath: /persistentvolumes
        env:
        - name: PROVISIONER_NAME
          value: nfs-client
        - name: NFS_SERVER
          value: 192.168.110.33
        - name: NFS_PATH
          value: /opt/app/nfs/mysql
      volumes:
      - name: nfs-client-root
        nfs:
          server: 192.168.110.33
          path: /opt/app/nfs/mysql