apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc1
  namespace: middleware
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-mysql