kind: ConfigMap
apiVersion: v1
metadata:
  name: mycnf
  namespace: mysql-cluster2
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
    mycnf.cnf: |
      [mysqld]
      max_connections=1500