apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret2
  namespace: mysql-cluster2
  labels:
    app: mysql2
type: Opaque
data:
  password: TnRpNTZAY29t 
  repl-user: bnRp # echo -n 'nti' | base64
  repl-pass: TnRpMTIzNDU2eG15Yw== # echo -n 'Nti123456xmyc' | base64