apiVersion: v1
kind: Service
metadata:
  name: mysql2
  namespace: mysql-cluster2
  labels:
    app: mysql2
spec:
  ports:
  - name: mysql2
    port: 3306
    targetPort: 3306
    nodePort: 33060
  selector:
    statefulset.kubernetes.io/pod-name: mysql-0
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-read2
  namespace: mysql-cluster2
  labels:
    app: mysql2
spec:
  ports:
  - name: mysql2
    port: 3306
    targetPort: 3306
    nodePort: 33070
  type: NodePort
  selector:
    app: mysql2