apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-single-config
  namespace: middleware
  labels:
    app: redis-single
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    requirepass redis123
    pidfile /data/redis-6379.pid