apiVersion: v1
kind: Service
metadata:
  name: redis-single
  namespace: middleware
  labels:
    app: redis-single
spec:
  type: NodePort
  ports:
  - name: redis-single
    port: 6379
    targetPort: 6379
    nodePort: 6379
  selector:
    app: redis-single