apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: public-service
  labels:
    app: redis-master
spec:
  type: NodePort
  ports:
  - name: redis-master
    port: 6379
    targetPort: 6379
    nodePort: 16379
  selector:
    app: redis-sentinel-master-ss